package com.guess.model;

public enum MessageType {
	SYSTEM, 
	FRIEND_APPLICATION, 
	FRIEND_APPLICATION_REPLAY,
	ORG_ATTENTION, 
	SHARE_QUESTION, 
	SHARE_QUESTION_REPLY, 
	ORG_APPLICATION, 
	QUESTION_REPORT
}
